export { SECTIONS, type SectionEntry } from './sectionsConfig'
export { LandingPage } from './LandingPage'
export { Section1_PhysicsOfSound } from './Section1_PhysicsOfSound'
export { Section2_PitchAndCents } from './Section2_PitchAndCents'
export { Section3_Harmonics } from './Section3_Harmonics'
export { Section4_Intervals } from './Section4_Intervals'
export { Section5_Scales } from './Section5_Scales'
export { Section6_Chords } from './Section6_Chords'
export { Section7_KeysAndCircleOfFifths } from './Section7_KeysAndCircleOfFifths'
export { Section8_ChordProgressions } from './Section8_ChordProgressions'
export { Section9_CreativeToolset } from './Section9_CreativeToolset'
